#!/bin/sh

exec >/root/setup.log 2>&1

. /lib/functions.sh


echo "(I) Start Setup"

mac=$(cat /sys/class/ieee80211/phy0/macaddress)

# Delete all wifi interfaces
while uci -q delete wireless.@wifi-iface[0]; do :; done

# Create an AP and mesh interface for each wifi device
config_wifi() {
	local ds="$1" #device section
	local wifi_device=`uci -q get wireless.$ds.device`
	local wifi_path=`uci -q get wireless.$ds.path`

	[ -z "$wifi_device" ] && wifi_device="$ds"

	echo "(I) Configure wifi device: '$wifi_device'"

	if [ `uci get wireless.$ds.channel` -gt 35 ]; then
		uci set wireless.$ds.channel=36
	else
		uci set wireless.$ds.channel=1
	fi

	uci set wireless.$ds.country='DE'
	uci set wireless.$ds.disabled='0'
	# Not a valid value, but will be ignored otherwise (for web ui)
	#uci set wireless.$ds.txpower='auto'

	# Mesh interface
	h="wireless.${wifi_device}_geomesh"
	uci set $h="wifi-iface"
	uci set $h.device="$wifi_device"
	uci set $h.mode="mesh"
	uci set $h.network="${wifi_device}_geomesh"
	uci set $h.mesh_id="mesh-id"
	uci set $h.mesh_fwding=0 # Disabled! Because we use our own routing protocol.

	# AP interface
	p="wireless.${wifi_device}_ap"
	uci set $p="wifi-iface"
	uci set $p.device="$wifi_device"
	uci set $p.mode=ap
	uci set $p.network=lan
	uci set $p.ssid="geomesh-${mac:15}"
	uci set $p.encryption="psk2" #none
	uci set $p.key="openwrt123"
}

config_load wireless
config_foreach config_wifi wifi-device

n="network.mesh"
uci set $n="interface"
uci set $n.ifname=tun0
uci set $n.proto=none

n="firewall.mesh_zone"
uci set $n="zone"
uci set $n.name="mesh"
uci add_list $n.network="mesh"
uci set $n.input="ACCEPT"
uci set $n.output="ACCEPT"
uci set $n.forward="ACCEPT"

n="firewall.mesh_forwarding"
uci set $n="forwarding"
uci set $n.src="mesh"
uci set $n.dest="wan"

uci add_list dhcp.lan.dhcp_option='6,8.8.8.8'

uci commit wireless
uci commit network
uci commit firewall
uci commit dhcp

/etc/init.d/geomesh enable
