#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1
PROG=/usr/bin/geomesh
OPTS=""

xappend() {
	local name="$2" value="$1"
	OPTS="$OPTS --${name//_/-} ${value//'/\\'}
"
}

append_opts_boolean() {
	local name value cfg="$1"; shift
	for name in $*; do
		config_get_bool value "$cfg" "$name" 0
		[ $value -gt 0 ] && xappend '' $name
	done
}

section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
	[ $enabled -gt 0 ]
}

start_instance() {
	local cfg="$1" option value

	section_enabled "$cfg" || return

	OPTS=""

	## --<option>
	for option in "tun_setup"; do
		config_get_bool value "$cfg" "$option" 0
		[ $value -gt 0 ] && xappend '' $option
	done

	# --<option> <value>
	for option in "protocol" "disable_stdin" "control" "gateway_id" "own_id" "tun_name" "verbosity"; do
		config_get value "$cfg" "$option"
		[ -n "$value" ] && xappend "$value" "$option"
	done

	config_list_foreach "$cfg" "peer" xappend "peer"
	config_list_foreach "$cfg" "ifname" xappend "ifname"

	procd_open_instance
	procd_set_param command $PROG $OPTS
	procd_set_param stderr 1
	procd_set_param stdout 1
	#procd_append_param command $OPTS
	procd_close_instance
}

start_service() {
	config_load 'geomesh'
	config_foreach start_instance 'geomesh'
}
