#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1
PROG=/usr/bin/geomesh
OPTS=""

xappend() {
	local name="$2" value="$1"
	OPTS="$OPTS--${name//_/-} ${value//'/\\'}
"
}

section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
	[ $enabled -gt 0 ]
}

start_instance() {
	local cfg="$1" protocol

	section_enabled "$cfg" || return

	OPTS=""

	# set protocol
	config_get protocol "$cfg" "protocol"
	[ -n "$protocol" ] && xappend "$protocol" "p"

	config_list_foreach "$cfg" "peer" xappend "peer"
	config_list_foreach "$cfg" "ifname" xappend "ifname"

	procd_open_instance
	procd_set_param command $PROG $OPTS
	procd_set_param stderr 1
	procd_set_param stdout 1
	#procd_append_param command $OPTS
	procd_close_instance
}

start_service() {
	config_load 'geomesh'
	config_foreach start_instance 'geomesh'
}

stop_service() {
	config_load 'geomesh'
	config_foreach stop_instance 'geomesh'
}
